[theme]
inherit = basic
stylesheet = css/clarity.css
pygments_style = clarity-dark
pygments_dark_style = clarity-dark
sidebars = sidebar.html

[options]
light_logo =
dark_logo =
sidebar_hide_name = False
navigation_with_keys = True
default_theme = system
show_toc_level = 2
font_stack = default
